<a href="https://colab.research.google.com/github/MikaDM07/IA-Demera-Micaela-/blob/main/Actibvidad_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Create an array with random values between 1 and 10
a = np.random.randint(1, 11, size=(3, 4))
b = np.random.randint(1, 11, size=(3, 4))

# Print the random array
print(a)
print(b)
print(a.shape)
print(b.shape)
print('adding numbers')
print(a+b)
print('substracting numbers')
print(a-b)
print('multiply numbers')
print(a*b)

print(np.add(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[ 4  2  8  8]
 [ 4 10  3  5]
 [ 1  1  6  8]]
[[ 2  2  5  7]
 [10  4  4  7]
 [ 7  6  4  3]]
(3, 4)
(3, 4)
adding numbers
[[ 6  4 13 15]
 [14 14  7 12]
 [ 8  7 10 11]]
substracting numbers
[[ 2  0  3  1]
 [-6  6 -1 -2]
 [-6 -5  2  5]]
multiply numbers
[[ 8  4 40 56]
 [40 40 12 35]
 [ 7  6 24 24]]
[[ 6  4 13 15]
 [14 14  7 12]
 [ 8  7 10 11]]
[[ 8  4 40 56]
 [40 40 12 35]
 [ 7  6 24 24]]


In [ ]:
a = np.random.randint(1, 11, size=(2, 3))
b = np.random.randint(1, 11, size=(3, 4))
print(a)
print(b)
print(np.dot(a,b))
print(a.dot(b))
print(a.shape)

[[10  4  2]
 [ 2  4 10]]
[[5 1 8 3]
 [9 7 1 5]
 [6 2 3 1]]
[[ 98  42  90  52]
 [106  50  50  36]]
[[ 98  42  90  52]
 [106  50  50  36]]
(2, 3)


In [ ]:
a = np.random.randint(1, 11, size=(2,2))
print(a.shape)
print(type(a))
print(a)
print(a.T)

(2, 2)
<class 'numpy.ndarray'>
[[2 3]
 [1 5]]
[[2 1]
 [3 5]]


In [ ]:
a = np.random.randint(1, 11, size=(4,3))
b = np.array([1,0,2])
print(a.shape)
print(b.shape)

c=np.empty_like(a)
print(a)
print(b)
print(c.shape)
print('---------------')
print(c)



(4, 3)
(3,)
[[ 9 10  1]
 [ 4  8  8]
 [ 5  5  4]
 [ 5  9  4]]
[1 0 2]
(4, 3)
---------------
[[ 8 10  1]
 [ 3  7  8]
 [ 2  3  9]
 [ 4  8  4]]


In [ ]:
for i in range(4):
  c[i,:]=a[i,:]+b

  print(a)
  print(b)
  print(c)

  c=a+b
  print(c)

[[ 9 10  1]
 [ 4  8  8]
 [ 5  5  4]
 [ 5  9  4]]
[1 0 2]
[[10 10  3]
 [ 5  8 10]
 [ 6  5  6]
 [ 6  9  6]]
[[10 10  3]
 [ 5  8 10]
 [ 6  5  6]
 [ 6  9  6]]
[[ 9 10  1]
 [ 4  8  8]
 [ 5  5  4]
 [ 5  9  4]]
[1 0 2]
[[10 10  3]
 [ 5  8 10]
 [ 6  5  6]
 [ 6  9  6]]
[[10 10  3]
 [ 5  8 10]
 [ 6  5  6]
 [ 6  9  6]]
[[ 9 10  1]
 [ 4  8  8]
 [ 5  5  4]
 [ 5  9  4]]
[1 0 2]
[[10 10  3]
 [ 5  8 10]
 [ 6  5  6]
 [ 6  9  6]]
[[10 10  3]
 [ 5  8 10]
 [ 6  5  6]
 [ 6  9  6]]
[[ 9 10  1]
 [ 4  8  8]
 [ 5  5  4]
 [ 5  9  4]]
[1 0 2]
[[10 10  3]
 [ 5  8 10]
 [ 6  5  6]
 [ 6  9  6]]
[[10 10  3]
 [ 5  8 10]
 [ 6  5  6]
 [ 6  9  6]]


In [ ]:
a=np.array([1,2,3])

print(a)
tmp=np.tile(a,(6,1))
print(tmp)

[1 2 3]
[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
a=np.random.randint(0,10, size=(6,6))
print(a)
aux=np.mean(a)
print(aux)
print(a.mean(axis=1))

[[4 7 8 9 5 3]
 [1 6 3 8 6 5]
 [9 0 4 0 3 7]
 [5 9 5 3 2 2]
 [9 5 4 0 8 6]
 [0 7 5 4 8 1]]
4.75
[6.         4.83333333 3.83333333 4.33333333 5.33333333 4.16666667]
