<a href="https://colab.research.google.com/github/MikaDM07/IA-Demera-Micaela-/blob/main/Clases_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np

# Create an array with random values between 1 and 10
a = np.random.randint(1, 11, size=(3, 4))
b = np.random.randint(1, 11, size=(3, 4))

# Print the random array
print(a)
print(b)
print(a.shape)
print(b.shape)
print('adding numbers')
print(a+b)
print('substracting numbers')
print(a-b)

print(np.add(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

print

[[ 3 10  1 10]
 [ 4 10  6  3]
 [ 9  9 10 10]]
[[ 4  8  6  8]
 [ 8  9 10  2]
 [ 6  4  3  3]]
(3, 4)
(3, 4)
adding numbers
[[ 7 18  7 18]
 [12 19 16  5]
 [15 13 13 13]]
substracting numbers
[[-1  2 -5  2]
 [-4  1 -4  1]
 [ 3  5  7  7]]
[[ 7 18  7 18]
 [12 19 16  5]
 [15 13 13 13]]
[[12 80  6 80]
 [32 90 60  6]
 [54 36 30 30]]
[[0.75       1.25       0.16666667 1.25      ]
 [0.5        1.11111111 0.6        1.5       ]
 [1.5        2.25       3.33333333 3.33333333]]


<function print>

In [8]:
a = np.random.randint(1, 11, size=(2,3))
b = np.random.randint(1, 11, size=(3,4))
print(a)
print(b)
print(np.dot(a,b))
print(a.dot(b))
print(a.shape)

[[10  6  4]
 [ 7 10  5]]
[[10 10  8  8]
 [ 3  5  4  3]
 [ 6  5  1  3]]
[[142 150 108 110]
 [130 145 101 101]]
[[142 150 108 110]
 [130 145 101 101]]
(2, 3)


In [ ]:
a = np.random.randint(1, 11, size=(2,2))
print(a. shape)
print(type (a))
print(a)
print(a.T)


In [12]:
a = np.random. randint(1, 11, size= (4,3))
b = np.array ([1,0,2])
print(a.shape)
print(b.shape)

c=np.empty_like(a)

print(a)
print(b)
print(c.shape)
print('-------------')
print(c)



(4, 3)
(3,)
[[ 7  4 10]
 [ 7  9  1]
 [ 8  9  5]
 [ 5  2  5]]
[1 0 2]
(4, 3)
-------------
[[4604930618986332160 4608308318706860032 4595172819793696085]
 [4608308318706860032 4602678819172646912 4607682818758614130]
 [4603579539098121011 4609434218613702656 4609434218613702656]
 [4612248968380809216 4614688418178968235 4614688418178968235]]


In [13]:
for i in range(4):
  c[i,:]=a[i,:] +b

print(a)
print(b)
print(c)

c=a+b
print(c)

[[ 7  4 10]
 [ 7  9  1]
 [ 8  9  5]
 [ 5  2  5]]
[1 0 2]
[[ 8  4 12]
 [ 8  9  3]
 [ 9  9  7]
 [ 6  2  7]]


In [19]:
a=np.array ([1,2,3])

print(a)

tmp=np.tile(a,(6,1))
print(tmp)

[1 2 3]
[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [23]:
a = np.random. randint(0, 10, size= (6,6))
print(a)
aux=np.mean(a)
print(aux)

print(a.mean(axis=1))

[[6 9 1 6 2 7]
 [8 1 0 8 2 7]
 [9 5 7 1 9 3]
 [3 2 0 3 6 3]
 [0 6 3 6 0 0]
 [9 4 3 1 0 0]]
3.888888888888889
[5.16666667 4.33333333 5.66666667 2.83333333 2.5        2.83333333]
