<a href="https://colab.research.google.com/github/MikaDM07/IA-Demera-Micaela-/blob/main/Exp_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
import numpy as np

# Check the NumPy version
print(np.__version__)

1.23.5


In [3]:
# Create a 1D array of numbers from 0 to 9
array_1d = np.arange(10)

print(array_1d)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
# Create a random vector of size 10
random_vector = np.random.rand(10)

# Find the index of the maximum value in the vector
max_index = np.argmax(random_vector)

# Replace the maximum value with 0
random_vector[max_index] = 0

print("Random vector with the maximum value replaced by 0:")
print(random_vector)

Random vector with the maximum value replaced by 0:
[0.53662638 0.16470707 0.92330781 0.51229366 0.         0.89886815
 0.57657801 0.03591234 0.17279199 0.58478381]


In [5]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

# To print the number 8
number_to_find = 8

indices = np.where(arr == number_to_find)

print("Indices of the number 8:")
print(indices)

found_value = arr[indices]
print("The number 8 is at position:", indices[0], indices[1])
print("Value at that position:", found_value)

Indices of the number 8:
(array([1]), array([2]))
The number 8 is at position: [1] [2]
Value at that position: [8]


In [6]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Use slicing to extract the numbers [3, 4, 5]
subset = arr[2:5]

print("The numbers [3, 4, 5] from the array:")
print(subset)


The numbers [3, 4, 5] from the array:
[3 4 5]


In [7]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Use slicing to extract the last 4 numbers
a = arr[-4:]

print("The last 4 numbers from the array:")
print(a)

The last 4 numbers from the array:
[4 5 6 7]


In [8]:
t = np.ones((2, 2), dtype=bool)

print(t)

[[ True  True]
 [ True  True]]


In [9]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Use boolean indexing to extract odd numbers
odd_numbers = arr[arr % 2 == 1]

print("Odd numbers from the array:")
print(odd_numbers)

Odd numbers from the array:
[1 3 5 7 9]


In [10]:
vector = np.arange(10, 50)

print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [11]:
vector = np.arange(10, 50)

# Reverse the vector
reversed_vector = vector[::-1]

print(reversed_vector)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [12]:
random_array = np.random.randint(0, 101, size=(10, 10))

# Find the minimum and maximum values
min_value = np.min(random_array)
max_value = np.max(random_array)

print("Random Array:")
print(random_array)
print("Minimum Value:", min_value)
print("Maximum Value:", max_value)

Random Array:
[[ 14  87  63  99  86  28  47  23 100  61]
 [ 98  27  57  83  61  33  29  14  62  22]
 [  6  74   5  89  34  92  81  22   6  27]
 [ 51   0  24  59  68  23   4  95  93  31]
 [ 95  89  92  45  82  60  29  19   1  84]
 [ 25  76  55  33  71  99  79  91   6   4]
 [100  70  41  85  90  15  34  67  23  93]
 [ 94  27   0  60  32  49  13  96  18  41]
 [ 97  49   2  96   4  71  92  40  50  63]
 [ 59  96  42  42  21  17  42  69  95  95]]
Minimum Value: 0
Maximum Value: 100


In [13]:
randon = np.random.rand(3, 3, 3)

print(randon)

[[[0.97386094 0.0036188  0.98105086]
  [0.81955929 0.91218075 0.02802072]
  [0.3027305  0.82489853 0.32792285]]

 [[0.67078717 0.09855695 0.75833483]
  [0.86871525 0.73067898 0.73607835]
  [0.27214216 0.1788734  0.55661589]]

 [[0.56089263 0.03345897 0.92026307]
  [0.69565535 0.29294524 0.81516577]
  [0.6998696  0.15794962 0.49835295]]]


In [14]:
import numpy as np

# Create or define your NumPy array (arr)
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Use boolean indexing to replace odd numbers with -1
arr[arr % 2 == 1] = -1

print("Modified array with odd numbers replaced by -1:")
print(arr)


Modified array with odd numbers replaced by -1:
[-1  2 -1  4 -1  6 -1  8 -1]


In [15]:
float_array = np.array([1.3, 2.5, 3.7, 4.2])

print(float_array)

[1.3 2.5 3.7 4.2]


In [16]:
arr_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# Reshape the 1D array into a 2D array with 2 rows
arr_2d = arr_1d.reshape(2, -1)

print("1D Array:")
print(arr_1d)

print("2D Array with 2 rows:")
print(arr_2d)

1D Array:
[1 2 3 4 5 6 7 8]
2D Array with 2 rows:
[[1 2 3 4]
 [5 6 7 8]]


In [17]:
Z1 = np.random.randint(0, 10, 10)
Z2 = np.random.randint(0, 10, 10)

# Find the common values between Z1 and Z2
common_values = np.intersect1d(Z1, Z2)

print("Array Z1:", Z1)
print("Array Z2:", Z2)
print("Common values:", common_values)


Array Z1: [1 3 0 5 5 4 8 2 3 3]
Array Z2: [9 8 7 8 3 5 0 4 3 2]
Common values: [0 2 3 4 5 8]


In [18]:
A = np.random.randint(0, 2, 5)
B = np.random.randint(0, 2, 5)

# Check if A and B are equal
are_equal = np.array_equal(A, B)

print("Array A:", A)
print("Array B:", B)
print("Are A and B equal?", are_equal)

Array A: [0 1 1 0 1]
Array B: [1 0 0 0 0]
Are A and B equal? False


In [19]:
a = np.array([0, 2, 5])
b = np.array([0, 2, 5])

# Stack arrays a and b vertically
stacked_array = np.vstack((a, b))

print("Array a:")
print(a)

print("Array b:")
print(b)

print("Stacked array (vertically):")
print(stacked_array)

Array a:
[0 2 5]
Array b:
[0 2 5]
Stacked array (vertically):
[[0 2 5]
 [0 2 5]]


In [20]:
a = np.array([0, 2, 5])
b = np.array([0, 2, 5])

# Stack arrays a and b horizontally
stacked_array = np.hstack((a, b))

print("Array a:")
print(a)

print("Array b:")
print(b)

print("Stacked array (horizontally):")
print(stacked_array)

Array a:
[0 2 5]
Array b:
[0 2 5]
Stacked array (horizontally):
[0 2 5 0 2 5]


In [21]:
tmp = np.arange(15)

# Create a boolean mask to identify elements between 5 and 10
mask = (tmp >= 5) & (tmp <= 10)

# Use the boolean mask to extract elements between 5 and 10
result = tmp[mask]

print("Array tmp:")
print(tmp)

print("Items between 5 and 10:")
print(result)

Array tmp:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
Items between 5 and 10:
[ 5  6  7  8  9 10]


In [22]:
def pair_max(a, b):
    """Get the element-wise maximum of two arrays a and b."""
    return np.maximum(a, b)

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

result = pair_max(a, b)
print(result)

[6 7 9 8 9 7 5]


In [23]:
arr = np.arange(9).reshape(3, 3)
print("Original array:")
print(arr)

# Swap columns 1 and 2
arr[:, [1, 2]] = arr[:, [2, 1]]

print("Array after swapping columns 1 and 2:")
print(arr)

Original array:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Array after swapping columns 1 and 2:
[[0 2 1]
 [3 5 4]
 [6 8 7]]


In [24]:
random_array = np.random.uniform(5, 10, size=(5, 3))

print(random_array)


[[5.37511051 8.96000475 6.21229261]
 [6.07196462 6.75030473 6.83925109]
 [8.99998811 7.86538424 9.52679216]
 [8.25794409 8.68301208 8.70655589]
 [7.49942824 7.90136627 7.90033412]]
