<a href="https://colab.research.google.com/github/MikaDM07/IA-Demera-Micaela-/blob/main/Numpy_1_de_Untitled1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
aux=np.array ([1,2,4,5])
print(aux)
print(aux.shape)


aux=np.array([[1,2,3,4],[1,2,3,4,]])
print (aux.shape)
print(aux)
print(type(aux))


tmp=np.full((4,4),5)
print(tmp)


tmp=np.eye(4,4)
print(tmp)

print('..........')
tmp=np.ones((4,4))
print(tmp)


[1 2 4 5]
(4,)
(2, 4)
[[1 2 3 4]
 [1 2 3 4]]
<class 'numpy.ndarray'>
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
..........
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [3]:
tmp=10*np.random.random((3,3))
print(tmp)

[[2.88877176 2.99654206 1.97654286]
 [5.51783586 3.34235571 6.06203982]
 [0.24360734 5.35380247 7.83477765]]


In [4]:
print(tmp[:2,:2])

[[2.88877176 2.99654206]
 [5.51783586 3.34235571]]


In [5]:
print(tmp[:2,1:3])

[[2.99654206 1.97654286]
 [3.34235571 6.06203982]]


In [9]:
print(tmp[:1,1])
print(tmp[2,2])
print(tmp[2,1:3])

[4.44963462]
9.812163870194912
[2.62361702 9.81216387]


In [17]:
tmp=10*np.random.random((3,3))
print(tmp)

[[1.29828215 1.64566023 4.96404741]
 [9.83819764 5.09457894 6.14138096]
 [6.18030616 7.92043885 8.77966267]]


In [22]:
mask=(tmp>=2)&(tmp<=4)


In [20]:
mask=tmp>5
print(tmp[mask])

[9.83819764 5.09457894 6.14138096 6.18030616 7.92043885 8.77966267]


In [21]:
tmp= np.random.randint(1, 101, (4, 4))
print(tmp)
mask =np.mod(tmp, 2) == 0
matriz_pares = tmp[mask]
print(tmp[mask])


[[53 44 31 53]
 [82 47 34 27]
 [26 43 60 28]
 [87 18  6 18]]
[44 82 34 26 60 28 18  6 18]
