<a href="https://colab.research.google.com/github/MikaDM07/IA-Demera-Micaela-/blob/main/Numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
a= np.random.randint(1, 11, (3, 4))
b= np.random.randint(1, 11, (3, 4))
print(a)
print(a.shape)
print(b)
print(b.shape)
print('adding numbers')
print(a+b)
print('subtracting numbers')
print(a-b)
print('multiplier numbers')
print(a*b)


print(np.add(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[7 9 5 7]
 [4 1 7 5]
 [9 3 4 7]]
(3, 4)
[[3 6 9 5]
 [1 2 4 2]
 [4 6 2 3]]
(3, 4)
adding numbers
[[10 15 14 12]
 [ 5  3 11  7]
 [13  9  6 10]]
subtracting numbers
[[ 4  3 -4  2]
 [ 3 -1  3  3]
 [ 5 -3  2  4]]
multiplier numbers
[[21 54 45 35]
 [ 4  2 28 10]
 [36 18  8 21]]
[[10 15 14 12]
 [ 5  3 11  7]
 [13  9  6 10]]
[[21 54 45 35]
 [ 4  2 28 10]
 [36 18  8 21]]
[[2.33333333 1.5        0.55555556 1.4       ]
 [4.         0.5        1.75       2.5       ]
 [2.25       0.5        2.         2.33333333]]


In [2]:
a = np.random.randint(1, 11, size=(2, 3))
b = np.random.randint(1, 11, size=(3, 4 ))

print(a)
print(a.shape)
print(b)
print(b.shape)
print(np.dot(a,b))

[[ 9  4  9]
 [10  8  8]]
(2, 3)
[[ 8  5 10  1]
 [ 5  2  1  5]
 [ 6  2  4 10]]
(3, 4)
[[146  71 130 119]
 [168  82 140 130]]


In [3]:
a= np.random.randint(1, 11, (2, 2))
print(a.shape)
print(type(a))
print(a)
print(a.T)

(2, 2)
<class 'numpy.ndarray'>
[[4 2]
 [2 2]]
[[4 2]
 [2 2]]


In [4]:
a= np.random.randint(1, 11, (4, 3))
b= np.array((1,0,2))
print(a)
print(a.shape)
print(b)
print(b.shape)

c=np.empty_like(a)

print(c.shape)
print('----------------')
print(c)

[[ 8  7  8]
 [10  3  9]
 [ 6  5  6]
 [ 4 10  4]]
(4, 3)
[1 0 2]
(3,)
(4, 3)
----------------
[[7 9 5]
 [7 4 1]
 [7 5 9]
 [3 4 7]]


In [5]:
for i in range(4):
  c[i,:]=a[i,:]+b

print(a)
print(b)
print(c)

c=a+b
print(c)

[[ 8  7  8]
 [10  3  9]
 [ 6  5  6]
 [ 4 10  4]]
[1 0 2]
[[ 9  7 10]
 [11  3 11]
 [ 7  5  8]
 [ 5 10  6]]
[[ 9  7 10]
 [11  3 11]
 [ 7  5  8]
 [ 5 10  6]]


In [6]:
a=np.array((1,2,3))

print(a)
tmp=np.tile(a,(6,1))
print(tmp)

[1 2 3]
[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [7]:
a= np.random.randint(0,10 , (6, 6))
print(a)
aux=np.mean(a)
print(aux)

print(a.mean(axis=1))
print(a.mean(axis=0))

[[4 7 1 6 9 6]
 [9 7 6 5 4 4]
 [8 9 5 2 4 6]
 [2 2 3 4 1 5]
 [0 4 3 3 9 1]
 [2 2 9 9 0 1]]
4.5
[5.5        5.83333333 5.66666667 2.83333333 3.33333333 3.83333333]
[4.16666667 5.16666667 4.5        4.83333333 4.5        3.83333333]
