<a href="https://colab.research.google.com/github/MikaDM07/IA-Demera-Micaela-/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
aux=np.array ([1,2,4,5])
print(aux)
print(aux.shape)

aux=np.array([[1,2,3,4],[1,2,3,4,]])
print (aux.shape)
print(aux)
print(type(aux))

tmp=np.zeros((4,4))
print(tmp)

tmp=np.full((4,4),5)
print(tmp)

tmp=np.eye(4,4)
print(tmp)

print('..........')
tmp=np.ones((4,4))
print(tmp)


[1 2 4 5]
(4,)
(2, 4)
[[1 2 3 4]
 [1 2 3 4]]
<class 'numpy.ndarray'>
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
..........
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [10]:
import numpy as np

a = np.random.randint(1, 10, size=(3,3))
b = np.random.randint(1, 10, size=(3,3))

print(a)
print(b)
print(a.shape)
print(b.shape)

print('Adding numbers')
print(a+b)

print('Subtracting numbers')
print(a-b)

print('Multiplication numbers')
print(a*b)

print('Add')
print(np.add(a,b))
print('Substract')
print(np.subtract(a,b))
print('Multiply')
print(np.multiply(a,b))
print('Divide')
print(np.divide(a,b))

[[8 5 2]
 [5 5 7]
 [3 2 8]]
[[8 5 9]
 [6 8 5]
 [8 2 1]]
(3, 3)
(3, 3)
Adding numbers
[[16 10 11]
 [11 13 12]
 [11  4  9]]
Subtracting numbers
[[ 0  0 -7]
 [-1 -3  2]
 [-5  0  7]]
Multiplication numbers
[[64 25 18]
 [30 40 35]
 [24  4  8]]
Add
[[16 10 11]
 [11 13 12]
 [11  4  9]]
Substract
[[ 0  0 -7]
 [-1 -3  2]
 [-5  0  7]]
Multiply
[[64 25 18]
 [30 40 35]
 [24  4  8]]
Divide
[[1.         1.         0.22222222]
 [0.83333333 0.625      1.4       ]
 [0.375      1.         8.        ]]
